### ISSUE TITLE
Incorrect association date range - stp=C entries get ignored

### ISSUE THREAD

**Issue by mk-fg** [open-track/dtd2mysql#20]
For latest timetable from atoc (ttis653.zip), had these GTFS trips created for P76279_P77109 association:
https://gist.github.com/mk-fg/bee3f96ac9815f6f5bb344d0081ab005#file-query-cif-gtfs-p76279_p77109-txt-L80-L85

Note the calendar timespan on the last highlighted line - it goes from 2017-05-21 to 2017-09-10 (on sundays) without any exception dates, while CIF timetable data has clear stp=C cancellation entries for this association, highlighted in the link just above that.

Both gtfs-webcheck and python implementation disagree with that (latter producing "2017-05-21 2017-08-27" range for gtfs trip), so looks like a bug somewhere in processing stp=C association entries, as they don't seem to have any effect on results in this particular case.

**Comment by mk-fg** [comment]
> Both gtfs-webcheck and python implementation disagree with that (latter producing "2017-05-21 2017-08-27" range for gtfs trip)

Doesn't change the issue, but found that python code for this case only produces different results when ignoring all trains except P76279/P77109, but adding P76271 into the mix (also joins to P77109) produces apparently-incorrect result as well, which is probably why I didn't spot this earlier - looks like a common bug for 3+ trains association case.

**Comment by linusnorton** [comment]
My implementation replaces the assoc schedule with the merged base+assoc schedule and in doing so keeps the original calendar of the assoc schedule. In this case the assoc schedule (P76279) should be replaced by the P76279_P77109 service, except on the days where the association is cancelled. 

That my take a bit of time to wrap my head around but I will get on it.

**Comment by linusnorton** [comment]
In investigating this issue I found that a bigger issue was that the associated schedule was being removed even if the association only applied to a sub-section of the calendar. There is only one issue with the association having exclude days (P76279_P77109) but many other cases where the association record does not cover the whole associated schedule.

The fix now correctly overlays the association record and creates clones of the associated schedule for any  parts that the association doesn't apply.
