### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by ian13** [open-track/dtd2mysql#29]
Fresh install using npm, when trying to launch dtd2mysql with any parameters throws out of memory error.

> ~$ dtd2mysql

<--- Last few GCs --->

     105 ms: Mark-sweep 1.4 (5.5) -> 1.4 (5.5) MB, 3.1 / 0.0 ms [allocation failure] [GC in old space requested].
     108 ms: Mark-sweep 1.4 (5.5) -> 1.4 (5.5) MB, 2.6 / 0.0 ms [allocation failure] [GC in old space requested].
     110 ms: Mark-sweep 1.4 (5.5) -> 1.3 (5.5) MB, 2.1 / 0.0 ms [allocation failure] [GC in old space requested].
     112 ms: Mark-sweep 1.3 (5.5) -> 1.3 (4.5) MB, 2.1 / 0.0 ms [last resort gc].
     114 ms: Mark-sweep 1.3 (4.5) -> 1.3 (4.5) MB, 2.1 / 0.0 ms [last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x3167b80d <JS Object>
    1: /* anonymous */(aka /* anonymous */) [fs.js:10] [pc=0x5be1d2dd] (this=0x316081d9 <undefined>,exports=0x54b77775 <an Object with map 0x3b209ac9>,require=0x31685f11 <JS Function NativeModule.require (SharedFunctionInfo 0x3168453d)>,module=0x54b77741 <a NativeModule with map 0x3b20e4b1>,__filename=0x54b77761 <String[5]: fs.js>,__dirname=0x316081d9 <undefined>)
    2: arguments adaptor frame: 4-...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [node]
 2: 0x8b64f83 [node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 4: v8::internal::Heap::FatalProcessOutOfMemory(char const*, bool) [node]
 5: v8::internal::Factory::NewMap(v8::internal::InstanceType, int, v8::internal::ElementsKind) [node]
 6: v8::internal::Map::RawCopy(v8::internal::Handle<v8::internal::Map>, int) [node]
 7: v8::internal::Map::Normalize(v8::internal::Handle<v8::internal::Map>, v8::internal::PropertyNormalizationMode, char const*) [node]
 8: v8::internal::JSObject::NormalizeProperties(v8::internal::Handle<v8::internal::JSObject>, v8::internal::PropertyNormalizationMode, int, char const*) [node]
 9: v8::internal::JSObject::OptimizeAsPrototype(v8::internal::Handle<v8::internal::JSObject>, v8::internal::PrototypeOptimizationMode) [node]
10: v8::internal::Map::SetPrototype(v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::Object>, v8::internal::PrototypeOptimizationMode) [node]
11: v8::internal::JSFunction::SetInitialMap(v8::internal::Handle<v8::internal::JSFunction>, v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::Object>) [node]
12: v8::internal::Factory::NewFunction(v8::internal::Handle<v8::internal::String>, v8::internal::Handle<v8::internal::Code>, v8::internal::Handle<v8::internal::Object>, v8::internal::InstanceType, int, bool, bool, bool) [node]
13: v8::internal::ApiNatives::CreateApiFunction(v8::internal::Isolate*, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::ApiNatives::ApiInstanceType) [node]
14: 0x84d9b6f [node]
15: v8::internal::ApiNatives::InstantiateFunction(v8::internal::Handle<v8::internal::FunctionTemplateInfo>) [node]
16: v8::FunctionTemplate::GetFunction(v8::Local<v8::Context>) [node]
17: v8::FunctionTemplate::GetFunction() [node]
18: node::Environment::SetMethod(v8::Local<v8::Object>, char const*, void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [node]
19: node::InitFs(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Context>, void*) [node]
20: 0x8b6b6f5 [node]
21: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [node]
22: 0x8512dca [node]
23: 0x851d9a1 [node]
24: 0x4ff0a7fe
25: 0x5be1d2dd
26: 0x4ff0bc36
27: 0x4ff3bf68
28: 0x4ff3b83f
29: 0x5be1b1cf
30: 0x4ff0bc36
31: 0x4ff3bf68
32: 0x4ff3b83f
33: 0x4ff3aed1
34: 0x4ff375e6
35: 0x4ff327de
36: 0x4ff218c3
37: 0x876bfcc [node]
38: v8::internal::Execution::Call(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int, v8::internal::Handle<v8::internal::Object>*) [node]
39: v8::Function::Call(v8::Local<v8::Context>, v8::Local<v8::Value>, int, v8::Local<v8::Value>*) [node]
40: v8::Function::Call(v8::Local<v8::Value>, int, v8::Local<v8::Value>*) [node]
41: node::LoadEnvironment(node::Environment*) [node]
42: node::Start(int, char**) [node]
43: __libc_start_main [/lib/i386-linux-gnu/libc.so.6]
Aborted

**Comment by linusnorton** [comment]
Hi, would you be able to tell me the version of node you have and the filename you are trying to import.

**Comment by ian13** [comment]
Using node v6.11.0 & npm 3.10.10

The same error is encountered with any parameters, e.g.
dtd2mysql
dtd2mysql -v
DATABASE_USERNAME=XXX DATABASE_PASSWORD=XXX DATABASE_NAME=XXX dtd2mysql --fares ./RJFAF607.ZIP

**Comment by linusnorton** [comment]
Unfortunately it requires node 8 or above to run. Could you upgrade and try again?

**Comment by ian13** [comment]
Upgraded node to v8.9.1

This seems to have solved the overt error, however process still dies with:

> Extracting ./RJFAF607.ZIP to /tmp/dtd/fares/
> Killed

**Comment by linusnorton** [comment]
How strange, I will bump the memory and release a new version.

**Comment by linusnorton** [comment]
I've just released a new version (3.4.1) that will use more memory but that did make me think - how much memory does your system have available?

**Comment by ian13** [comment]
Upgraded to 3.4.1

System memory is 
> $ free
>              total       used       free     shared    buffers     cached
> Mem:        507616     301488     206128      24628         72      42684
> -/+ buffers/cache:     258732     248884
Swap:            0          0          0

**Comment by linusnorton** [comment]
If I'm reading that correctly you have roughly 200~MB of memory free which I don't think will be enough. Is there any chance that you can free up some memory or try on a different machine?

**Comment by ian13** [comment]
You're quite right - 200MB available isn't sufficient.

Creating a 1 GB swapfile dealt with the issue :)
