### ISSUE TITLE
Stops with weird arrival_time/departure_time combinations

### ISSUE THREAD

**Issue by mk-fg** [open-track/dtd2mysql#3]
Spotted one such for C74098, where one of the produced trips have this stop sequence:

    GLC[23:15] - MTH[23:29/23:30] - **CRS[23:49/23:47]** -
    CAR[1+01:39/1+01:44] - PRE[1+03:03/1+03:09] - WBQ[1+03:39/1+03:41] -
    WFJ[1+06:43/1+06:44] - EUS[1+07:07]

Emphasis on "CRS[23:49/23:47]".

CIF data has no public_arrival_time, but has public_departure_time=23:47 and scheduled_arrival_time=23:49.

Didn't check how many of such quirks are in the data, but I think it indicates that correct logic for interpreting arr/dep times might be:

    Either use scheduled-time (for non-public stops) or public-time
    (for public ones), but don't mix them for same stop.

Based purely on this mismatch in CIF data though.

**Comment by mk-fg** [comment]
Somewhat similar case:
https://gist.github.com/mk-fg/f3f7db87f84485b3aad1d6ab7af137de

But here ts implementation has this stop sequence:

    ... - CDQ[19:04/19:06] - CDF[19:12/1+19:11] - CDQ[19:14/19:15] - ...

And public times in schedule records below clearly show that 19:11 is scheduled_departure_time.

If above "CRS[23:49/23:47]" mildly confusing, here departure time seem to be clearly broken and non-sequential, being shifted by whole day like that.

**Comment by mk-fg** [comment]
> And public times in schedule records below clearly show that 19:11 is scheduled_departure_time.

My bad, they don't, must've mistyped something when checking.

There are genuinely 19:11 and 19:12 there, and after association is applied, CDF stop in the resulting schedule ends up having arrival=19:12 and departure=19:11, so it seem to be an entirely separate issue, guess I'll open it as such.

Apologies for confusion, please disregard previous comment message and see #4.

**Comment by linusnorton** [comment]
The data is rather odd here - the scheduled arrival time is earlier than the public departure time. I guess I will need a sanity check for that.

**Comment by linusnorton** [comment]
I have resolved this issue by implementing some logic that says - if either the public dep/arr time is specified use that. If neither are specified use the scheduled times.
