### ISSUE TITLE
RGK MODE_CODE incorrectly specified as not nullable?

### ISSUE THREAD

**Issue by eoghanmurray** [open-track/dtd2mysql#9]
I'm getting an error with an import of the test Routeing download file `RJRG0281.RGK`

The third line of data contains the following:
`00003,D,I,SRA,N,,`
with an empty 5th position in the CSV record.
From the feed spec (RSPS5047) this seems valid as the ENTRY_TYPE is `I`; ("The Mode Code must be specified where Entry Type is ‘L’ or ‘N’.")

Should `false` for nullable be changed to `true` here:
https://github.com/open-track/dtd2mysql/blob/master/config/routeing/file/RGK.ts#L24
?

I can create a pull request unless there's something I'm missing.

**Comment by eoghanmurray** [comment]
Pull request if it's just a simple case of setting it to be nullable (that worked for me):
https://github.com/open-track/dtd2mysql/pull/10

**Comment by linusnorton** [comment]
Thanks for the PR, it's merged now
